name: sih_mockup
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  location: ^8.0.1
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  http: ^1.5.0
  path_provider: ^2.1.4
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_database: ^12.0.1  # <-- added safely
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  web3dart: ^2.7.3
  encrypt: ^5.0.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/abi.json
